services:
  - type: web
    name: agroprix-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python import_csv.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./data/agroprix.db
      - key: PORT
        value: "10000"
